# Generated by Django 5.2.11 on 2026-02-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_contentauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='discarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
