# Generated by Django 5.2.11 on 2026-02-16 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_deploymentlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contentauditlog',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When content was deleted', null=True),
        ),
        migrations.AddField(
            model_name='contentauditlog',
            name='redirect_target',
            field=models.CharField(blank=True, default='', help_text='URL path to redirect deleted content (e.g., /articles or /articles/category). Empty for intentional 404.', max_length=500),
        ),
        migrations.AddIndex(
            model_name='contentauditlog',
            index=models.Index(fields=['action', 'deleted_at'], name='chat_conten_action_43b12f_idx'),
        ),
    ]
