# Generated by Django 5.2.11 on 2026-02-06 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('group_lead', 'Group Lead'), ('contributor', 'Contributor')], default='contributor', max_length=20)),
                ('local_group', models.CharField(blank=True, choices=[('brighton', 'Brighton'), ('london', 'London'), ('oxford', 'Oxford'), ('pennines', 'Pennines'), ('scotland', 'Scotland'), ('solent', 'Solent')], default='', help_text='Required for group_lead role. Must match a localGroups slug.', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
