# Generated by Django 5.2.11 on 2026-03-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='header_video',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
