# Generated by Django 5.2.9 on 2026-03-10 14:00

from django.db import migrations


# Map old image paths to new organised paths
PATH_RENAMES = {
    # Local group headers → local-groups/
    '/images/brighton-pavilion.avif': '/images/local-groups/brighton.avif',
    '/images/london-westminster.webp': '/images/local-groups/london.webp',
    '/images/edinburgh-castle.webp': '/images/local-groups/edinburgh.webp',
    '/images/cardiff-castle.webp': '/images/local-groups/cardiff.webp',
    # Event images → local-groups/
    '/images/bill-mitchell-event.webp': '/images/local-groups/bill-mitchell-event.webp',
    '/images/pintonomics-edinburgh.webp': '/images/local-groups/pintonomics-edinburgh.webp',
    '/images/scotland-festival-of-economics.webp': '/images/local-groups/scotland-festival-of-economics.webp',
    # Briefing thumbnails → briefings/
    '/images/income-security.webp': '/images/briefings/income-security.webp',
    '/images/nature-of-money.webp': '/images/briefings/nature-of-money.webp',
    '/images/question-about-economics.webp': '/images/briefings/question-about-economics.webp',
    '/images/symmetry-that-blinds.webp': '/images/briefings/symmetry-that-blinds.webp',
    # Research → research/
    '/images/job-guarantee-video-thumb.webp': '/images/research/job-guarantee-video-thumb.webp',
}


def update_paths(apps, schema_editor):
    """Update image paths in all content models."""
    models_fields = [
        ('Article', 'thumbnail'),
        ('Briefing', 'thumbnail'),
        ('News', 'thumbnail'),
        ('LocalGroup', 'header_image'),
        ('LocalEvent', 'image'),
    ]

    for model_name, field_name in models_fields:
        Model = apps.get_model('content', model_name)
        for old_path, new_path in PATH_RENAMES.items():
            Model.objects.filter(**{field_name: old_path}).update(**{field_name: new_path})


def revert_paths(apps, schema_editor):
    """Revert image paths."""
    models_fields = [
        ('Article', 'thumbnail'),
        ('Briefing', 'thumbnail'),
        ('News', 'thumbnail'),
        ('LocalGroup', 'header_image'),
        ('LocalEvent', 'image'),
    ]

    for model_name, field_name in models_fields:
        Model = apps.get_model('content', model_name)
        for old_path, new_path in PATH_RENAMES.items():
            Model.objects.filter(**{field_name: new_path}).update(**{field_name: old_path})


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_news_header_video'),
    ]

    operations = [
        migrations.RunPython(update_paths, revert_paths),
    ]
